# Static path /__BASE_PATH__/ served from __ROOT__
# This file must be included *inside* a server { } block (the TLS server).
location = /__BASE_PATH__ {
    return 301 /__BASE_PATH__/;
}

location ^~ /__BASE_PATH__/ {
    alias __ROOT__/;
    index index.html;
}
